[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spikecurate"
version = "0.1.0"
description = "Package to curate single-units recorded with dense probes from SpikeInterface extractors"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [{ name = "steeve laquitaine", email = "laquitainesteeve@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "spikeinterface==0.100.8",
    "numpy>=1.21",
    "pandas>=1.4",
    "scikit-learn>=1.0",
    "statsmodels>=0.13",
    "matplotlib>=3.5",
    "seaborn>=0.12",
]

[project.optional-dependencies]
test = ["pytest>=7"]

[tool.setuptools.packages.find]
where = ["src"]
